### ISSUE TITLE
why not use generic arrays?

### ISSUE THREAD

**Issue by robatipoor** [jkelleyrtp/pipette#1]
thank you for great idea but I wonder why arrays are not used instead of tuple, does this implementation have an advantage? 
sample code :
```rust
pub fn pip<T, F, const N: usize>(init: T, funcs: [F; N]) -> T
where
    F: FnOnce(T) -> T,
{
    let mut r = init;
    for f in funcs {
        r = f(r)
    }
    r
}
```

**Comment by jkelleyrtp** [comment]
Thanks for the question!

The tuple is used because the closures are all different types. If an array were used, all the closures would have to be the exact same type - but according to Rust, no two closures are the same type. 

Plus, in your example, both the input and output value would need to be the same type (T), but many functions transform from one type to another.
